Science design 462 [WIP]
space-concordia-robotics/robotics-prototype pull request #469
Opened 2020-10-14 20:44 UTC by MartensCedric

# Assignee Section

## Description
Design and skeleton of teensy science code.

- Design documents in PlantUML code in `docs/`
- Added Skeleton code for C++

### Steps for Testing
1. Copy paste the diagram code in here to see a pic http://www.plantuml.com/plantuml/uml/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000
2. Run the science code and make sure it compiles https://github.com/space-concordia-robotics/robotics-prototype/wiki/Building-the-C---code

closes #462 

The approval from all software team leads is necessary before merging.

# Reviewer Section

Aside from local testing and the General Integration Test it is implied that static analysis should be included in the verification process.

- [ ] Local Test Performed Successfully
- [ ] [General Integration Test](https://docs.google.com/document/d/1ug0CpA1cIzURP8DDFSvCt2CEJJSwJ6Ta6B1LG_hYk6I/edit) Performed Successfully

For Pull Requests that do not include code changes, it is not required to perform the tests above.

2020-10-14 20:45 UTC, MartensCedric commented
draft PR because I'm not quite done

2020-10-17 16:33 UTC, MartensCedric commented on robot/rover/science/src/commands/CommandCenter.cpp
> +}
this is untested, I plan to make a Unit test for it with issue #471 asap

2020-10-17 16:42 UTC, MartensCedric commented on robot/rover/science/src/commands/CommandCenter.cpp
> +}
keep in mind that this is fully out of scope of this PR which aims to just propose a design, this is just bonus code

2020-10-20 01:47 UTC, ginywiny commented
1. Copy pasting the diagram codes returned the Embedded Science Subsystem and Base Station diagrams in picture format.

2. Code compiled successfully for all modules and are visible in the /robot/rover/build directory as instructed in the CMake instructions. 

Everything compiled successfully without errors, so this is good on my part.

2020-10-20 01:49 UTC, ginywiny reviewed
1. Copy pasting the diagram codes returned the Embedded Science Subsystem and Base Station diagrams in picture format.

2. Code compiled successfully for all modules and are visible in the /robot/rover/build directory as instructed in the CMake instructions.

Everything compiled successfully without errors, so this is good on my part.

2020-10-20 02:04 UTC, ginywiny submitted a review, later dismissed
Testing steps 1 and 2 ran properly. I approve.

2020-11-01 19:50 UTC, steamypotato commented on robot/rover/science/include/Fan.h
> +        int fanPWM;
Since PWM goes from 0-255 why not use uint8 instead of int (which is 2-4 bytes signed)

2020-11-01 20:03 UTC, steamypotato requested changes

2020-11-01 20:03 UTC, steamypotato commented on robot/rover/science/raman.ino
> +const int NUMBER_OF_STOPPABLES = 5;
do we need ints for this

2020-11-02 02:15 UTC, MartensCedric commented on robot/rover/science/include/Fan.h
> +        int fanPWM;
good point

2020-11-02 02:24 UTC, MartensCedric commented on robot/rover/science/include/Laser.h
> +class Laser : public Stoppable, public Updatable {
changed the UML to reflect this

2020-11-03 01:45 UTC, steamypotato approved these changes

2020-11-07 18:46 UTC, ginywiny approved these changes
Good, yes. Approved

2020-11-07 18:47 UTC, merged