Update ci to use ros2 for building instead of ros 601
space-concordia-robotics/robotics-prototype pull request #609
Opened 2023-06-24 19:11 UTC by OZiad

# Assignee Section

## Description
Update ROS 2 installation script to verify and install ROS Humble and change CI to use old Arduino script

2023-07-01 18:59 UTC, steamypotato requested changes

2023-07-01 18:59 UTC, steamypotato commented on scripts/ros_install.sh
EnvironmentSetup.sh references 'install_ros.sh' (line 21), but file is called is 'ros_install.sh'

2023-07-01 18:59 UTC, steamypotato commented on EnvironmentSetup.sh
line 39 (rosdep install -i --from-path src --rosdistro foxy -y) should be updated for ROS humble

2023-07-08 18:45 UTC, VimFreeman commented on scripts/ros_install.sh
> +sudo apt -qq upgrade
the -y is necessary or else script will stall until user confirms the upgrade

2023-07-08 19:13 UTC, VimFreeman commented
![image](https://github.com/space-concordia-robotics/robotics-prototype/assets/34408555/bbb41361-4d30-4fbd-a5ba-5fb406486013)

2023-07-09 20:15 UTC, VimFreeman commented
@OZiad did you try to run EnvironmentSetup.sh in a new user?

2023-07-10 00:14 UTC, OZiad commented
> @OZiad did you try to run EnvironmentSetup.sh in a new user?

Yea but I'm not able to replicate the CMake error, it seems to run fine on the test user I made after fixing the ros dependency issue

2023-07-22 18:59 UTC, merged